services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html
    networks:
      - symfony
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.25
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_started
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306" # port host -> port conteneur
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:

networks:
  symfony:
    driver: bridge
